name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale. Feel free to re-open it if it requires more attention'
          stale-pr-message: 'This PR is stale. Feel free to re-open it if it requires more attention.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'enhancement,bug'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'in progress'
